-- =========================================================
-- Split prod_items: nowe tabele
-- Uruchom PRZED migrate_prod_items_to_split_tables.py
-- =========================================================

CREATE TABLE prod_configurations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  species VARCHAR(50) NOT NULL,
  technology VARCHAR(50) NOT NULL,
  wood_class VARCHAR(10) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_config (species, technology, wood_class)
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE prod_orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  baselinker_order_id INT NOT NULL UNIQUE,
  internal_order_number VARCHAR(20) NOT NULL,
  baselinker_status_id INT NULL,
  payment_date DATETIME NULL,
  client_order_number VARCHAR(200) NULL,
  order_notes TEXT NULL,
  client_name VARCHAR(255) NULL,
  client_email VARCHAR(255) NULL,
  client_phone VARCHAR(50) NULL,
  delivery_address TEXT NULL,
  delivery_method VARCHAR(255) NULL,
  delivery_fullname VARCHAR(255) NULL,
  delivery_company VARCHAR(255) NULL,
  delivery_city VARCHAR(100) NULL,
  delivery_postcode VARCHAR(20) NULL,
  delivery_country_code VARCHAR(10) NULL,
  override_delivery_method VARCHAR(255) NULL,
  logistics_completed_at DATETIME NULL,
  shipping_package_id INT NULL,
  shipping_tracking_number VARCHAR(100) NULL,
  shipping_courier_name VARCHAR(100) NULL,
  shipping_price DECIMAL(10,2) NULL,
  shipping_label_base64 LONGTEXT NULL,
  shipping_created_at DATETIME NULL,
  attachment_file_name VARCHAR(255) NULL,
  attachment_file_url TEXT NULL,
  sync_source ENUM('baselinker_auto','manual_entry') DEFAULT 'baselinker_auto',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_client_name (client_name),
  KEY idx_payment_date (payment_date),
  KEY idx_baselinker_status (baselinker_status_id),
  KEY idx_logistics_completed (logistics_completed_at)
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE prod_products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_id INT NOT NULL,
  configuration_id INT NULL,
  short_product_id VARCHAR(20) NOT NULL UNIQUE,
  product_sequence_in_order INT NOT NULL,
  baselinker_product_id VARCHAR(50) NULL,
  original_product_name TEXT NOT NULL,
  parsed_length_cm DECIMAL(10,2) NULL,
  parsed_width_cm DECIMAL(10,2) NULL,
  parsed_thickness_cm DECIMAL(10,2) NULL,
  parsed_finish_state VARCHAR(50) NULL,
  parsed_finish_type VARCHAR(20) NOT NULL DEFAULT 'surowe',
  parsed_finish_color_type VARCHAR(20) NULL,
  parsed_finish_gloss VARCHAR(20) NULL,
  parsed_finish_color VARCHAR(50) NULL,
  parsed_edge_processing TINYINT(1) NOT NULL DEFAULT 0,
  cut_to_size TINYINT(1) NOT NULL DEFAULT 1,
  parsed_edge_type VARCHAR(20) NULL,
  parsed_edge_radius INT NULL,
  parsed_edge_angle INT NULL,
  parsed_edge_letters JSON NULL,
  edge_svg TEXT NULL,
  shape_svg TEXT NULL,
  lamella_direction INT NULL,
  quote_item_detail_id INT NULL,
  thickness_group VARCHAR(10) NULL,
  volume_m3 DECIMAL(10,6) NULL,
  unit_price_net DECIMAL(10,2) NULL,
  total_value_net DECIMAL(10,2) NULL,
  quantity INT NOT NULL DEFAULT 1,
  current_status ENUM('czeka_na_wyciecie','czeka_na_skladanie','czeka_na_kompletacje','czeka_na_sklejanie','czeka_na_formatowanie','czeka_na_wykanczanie','czeka_na_lakiernie','czeka_na_logistyke','czeka_na_pakowanie','spakowane','anulowane','wstrzymane','w_realizacji') NOT NULL DEFAULT 'czeka_na_wyciecie',
  deadline_date DATE NULL,
  days_until_deadline INT NULL,
  priority_rank INT NULL,
  priority_manual_override TINYINT(1) DEFAULT 0,
  is_priority TINYINT(1) DEFAULT 0,
  quantity_done_cutting INT NOT NULL DEFAULT 0,
  quantity_done_assembly INT NOT NULL DEFAULT 0,
  quantity_done_completion INT NOT NULL DEFAULT 0,
  quantity_done_gluing INT NOT NULL DEFAULT 0,
  quantity_done_formatting INT NOT NULL DEFAULT 0,
  quantity_done_finishing INT NOT NULL DEFAULT 0,
  quantity_done_painting INT NOT NULL DEFAULT 0,
  quantity_done_packaging INT NOT NULL DEFAULT 0,
  cutting_completed_at DATETIME NULL,
  assembly_completed_at DATETIME NULL,
  completion_completed_at DATETIME NULL,
  gluing_completed_at DATETIME NULL,
  formatting_completed_at DATETIME NULL,
  finishing_completed_at DATETIME NULL,
  painting_completed_at DATETIME NULL,
  packaging_completed_at DATETIME NULL,
  label_printed_at DATETIME NULL,
  label_print_count INT NOT NULL DEFAULT 0,
  production_notes TEXT NULL,
  quality_issues TEXT NULL,
  created_at DATETIME NULL,
  updated_at DATETIME NULL,
  KEY idx_order (order_id),
  KEY idx_config (configuration_id),
  KEY idx_status (current_status),
  KEY idx_priority_rank (priority_rank),
  KEY idx_deadline (deadline_date),
  KEY idx_is_priority (is_priority),
  CONSTRAINT fk_product_order FOREIGN KEY (order_id) REFERENCES prod_orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_product_config FOREIGN KEY (configuration_id) REFERENCES prod_configurations(id)
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
